WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FBEC0470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/51dd935e-c9ec-4ab3-b8c5-2d27e161b747
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FBDDA810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/51dd935e-c9ec-4ab3-b8c5-2d27e161b747
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FBDF91F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/51dd935e-c9ec-4ab3-b8c5-2d27e161b747