WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:127 The msedgedriver version (125.0.2535.51) detected in PATH at C:\Users\dell\AppData\Local\Programs\Python\Python312\Scripts\msedgedriver.exe might not be compatible with the detected MicrosoftEdge version (126.0.2592.61); currently, msedgedriver 126.0.2592.68 is recommended for MicrosoftEdge 126.*, so it is advised to delete the driver in PATH and retry
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FBE9D310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f2a215097eaa57b7fc9e2fdc76fa4bbf
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FBE9DF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f2a215097eaa57b7fc9e2fdc76fa4bbf
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FBE9F440>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f2a215097eaa57b7fc9e2fdc76fa4bbf