WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020BF2224860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2159c206-64ae-4355-a856-b30cbae8af96
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020BF213ACC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2159c206-64ae-4355-a856-b30cbae8af96
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020BF2157530>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2159c206-64ae-4355-a856-b30cbae8af96