WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FBEC1790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3551065a-a97b-4468-9a32-4b966be06f2b
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FBEC0680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3551065a-a97b-4468-9a32-4b966be06f2b
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000230FBEC06E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3551065a-a97b-4468-9a32-4b966be06f2b