WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019C5CFDD220>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ebdfed43-5b6a-456a-970a-d22aa28864f9
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019C5CF1BB90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ebdfed43-5b6a-456a-970a-d22aa28864f9
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019C5CF1B740>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ebdfed43-5b6a-456a-970a-d22aa28864f9