{"name": "test_login_without_entering_credentials[firefox]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\chromedriver.exe unexpectedly exited. Status code was: 1", "trace": "request = <SubRequest 'setup_and_teardown' for <Function test_login_without_entering_credentials[firefox]>>\n\n    @pytest.fixture(params=[\"chrome\",\"firefox\",\"edge\"])\n    def setup_and_teardown(request):\n      #make drive as global, Otherwise we will get problem\n      global driver\n      if request.param == \"chrome\":\n          driver = webdriver.Chrome(options=options)\n      elif request.param == \"firefox\":\n>         driver = webdriver.Firefox(options=options)\n\nconftest.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py:62: in __init__\n    self.service.start()\nC:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:102: in start\n    self.assert_process_still_running()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.firefox.service.Service object at 0x0000017D48A56300>\n\n    def assert_process_still_running(self) -> None:\n        \"\"\"Check if the underlying process is still running.\"\"\"\n        return_code = self.process.poll()\n        if return_code:\n>           raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\nE           selenium.common.exceptions.WebDriverException: Message: Service C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\chromedriver.exe unexpectedly exited. Status code was: 1\n\nC:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py:115: WebDriverException"}, "parameters": [{"name": "setup_and_teardown", "value": "'firefox'"}], "start": 1717903763816, "stop": 1717903763816, "uuid": "210924bd-75b3-4430-a450-06b4a654d7fb", "historyId": "6e058f201e86f3157984514ca4b659d1", "testCaseId": "4a3732509221fe895c7c3241bd5dd62f", "fullName": "sample.test_Login.TestLogin#test_login_without_entering_credentials", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "sample"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-4222FVV"}, {"name": "thread", "value": "9536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "sample.test_Login"}]}