WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019C5CFDCC80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/32a54f9b-8a11-4f62-a0ee-59669d322449
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019C5CFDC290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/32a54f9b-8a11-4f62-a0ee-59669d322449
WARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019C5CFDCB30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/32a54f9b-8a11-4f62-a0ee-59669d322449